trajectory_execution:
  allowed_execution_duration_scaling: 1.0
  allowed_goal_duration_margin: 1000.0
  allowed_start_tolerance: 0.01

moveit_controller_manager: moveit_ros_control_interface/Ros2ControlMultiManager
controller_service_call_timeout: 10.0

octomap:
  enabled: false
